"""Add keywords and phone columns

Revision ID: 3d0153c93b8e
Revises: a46aebae954b
Create Date: 2026-03-12 12:59:03.358805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '3d0153c93b8e'
down_revision: Union[str, Sequence[str], None] = 'a46aebae954b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clinics",
        sa.Column(
            "keywords",
            sa.String(length=255),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clinics", "keywords")
    # ### end Alembic commands ###
